language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN=476cff19244a1e3f6c75f1b8064bf7909eaec07a28b6120cc865154f9f8dd6c1"
install:
  - "npm install grunt-cli codeclimate-test-reporter -g"
  - "npm install"
script:
  - "grunt ci"
node_js:
  - "4"
  - "5"
  - "6"
cache:
  directories:
    - "node_modules"
